name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to version 4

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v3  # Updated to version 3
        with:
          node-version: '20'  # Using Node.js version 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn pkg

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.7.0

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ${{steps.build_changelog.outputs.changelog}}
          draft: true
          prerelease: true
          files: release/*.tar.gz
